name: base
channels:
  - defaults
dependencies:
  - conda
  - python=3.8
  - menuinst
  - console_shortcut
  - powershell_shortcut
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda==2020.11=py38_0
  - anaconda-navigator
  - navigator-updater
  - pyproj=2.4.2.post1
  - descartes=1.1.0
  - geopy=2.0.0
  - geomet
  - plotly
